import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { api, ApiError, brl, get, qs } from './api';
import { useAuth } from './auth';
import { BarList, Kpi, LineChart, MUTED, SERIES, fmt } from './charts';
import { ProductPick } from './commercial';

const today = () => new Date().toISOString().slice(0, 10);
const addDays = (n: number) => new Date(Date.now() + n * 86400000).toISOString().slice(0, 10);
const num = (v: any) => Number(v ?? 0);
const Err = ({ e }: { e: string }) => (e ? <div className="err">{e}</div> : null);
const pct = (v: any) => (v == null ? '—' : `${num(v).toLocaleString('pt-BR', { maximumFractionDigits: 1 })}%`);
const Flag = ({ ok, label }: { ok: boolean | null | undefined; label?: string }) => (ok == null ? <span className="muted">{label ?? '—'}</span> : <span className={`pill ${ok ? 'green' : 'red'}`}>{ok ? '✔' : '✖'} {label}</span>);
const date = (v: any) => (v ? String(v).slice(0, 10).split('-').reverse().join('/') : '—');

// ---------------------------------------------------------------- Executivo
export function BiExecutive() {
  const [d, setD] = useState<any>(null); const [err, setErr] = useState('');
  useEffect(() => { get('/bi/executive').then(setD).catch((e) => setErr(e.message)); }, []); if (!d) return <Err e={err} />;
  const h = d.highlights; const g = h.goals;
  return <><h1>BI — Visão do dono</h1><p className="sub">As perguntas de gestão respondidas com os dados do sistema. Cada resposta mostra de onde vem o número e leva à tela de detalhe. Estimativas estão identificadas como tal.</p>
    <div className="grid kpis" style={{ marginBottom: 14 }}><Kpi label="Faturamento (30 dias)" value={brl(h.revenue)} delta={h.revenue_delta_pct} /><Kpi label="Margem bruta" value={pct(h.gross_margin_pct)} status={g.margin_pct ? (g.margin_pct.ok ? 'ok' : 'bad') : null} sub={g.margin_pct ? `meta ${g.margin_pct.target}%` : <Link to="/bi/metas">definir meta</Link>} />
      <Kpi label="Meta de faturamento do mês" value={g.revenue ? `${g.revenue.pct}%` : '—'} sub={g.revenue ? `esperado ${g.revenue.expected_pct}% · projeção ${brl(g.revenue.projected)}` : <Link to="/bi/metas">definir meta</Link>} />
      <Kpi label="Estoque" value={brl(h.stock_value)} sub={h.turnover != null ? `giro ${h.turnover}x/ano` : ''} /><Kpi label="Inadimplência" value={pct(h.delinquency_pct)} /><Kpi label="Caixa" value={brl(h.cash)} /></div>
    <table><thead><tr><th>Pergunta</th><th>Resposta</th><th>Origem do número</th><th /></tr></thead><tbody>{d.answers.map((a: any) => <tr key={a.q}><td style={{ width: '24%' }}><b>{a.q}</b></td><td>{a.a}</td><td className="muted" style={{ width: '26%' }}>{a.source}</td><td><Link to={a.link}>detalhar →</Link></td></tr>)}</tbody></table></>;
}

// ---------------------------------------------------------------- Comercial
function PeriodBar({ f, setF, extra }: { f: any; setF: (x: any) => void; extra?: React.ReactNode }) {
  const preset = (label: string, from: string, to = today()) => <button key={label} className={f.from === from && f.to === to ? 'primary' : ''} onClick={() => setF({ ...f, from, to })}>{label}</button>;
  return <div className="toolbar">{preset('7 dias', addDays(-6))}{preset('30 dias', addDays(-29))}{preset('90 dias', addDays(-89))}{preset('Mês', today().slice(0, 7) + '-01')}{preset('Ano', today().slice(0, 4) + '-01-01')}
    <input type="date" style={{ maxWidth: 150 }} value={f.from} onChange={(e) => setF({ ...f, from: e.target.value })} /><input type="date" style={{ maxWidth: 150 }} value={f.to} onChange={(e) => setF({ ...f, to: e.target.value })} />
    {f.compare != null && <select style={{ width: 190 }} value={f.compare} onChange={(e) => setF({ ...f, compare: e.target.value })}><option value="previous">vs. período anterior</option><option value="year">vs. mesmo período do ano anterior</option><option value="none">sem comparação</option></select>}{extra}</div>;
}

export function BiCommercial() {
  const [f, setF] = useState({ from: addDays(-29), to: today(), compare: 'previous', channel: '' }); const [d, setD] = useState<any>(null); const [err, setErr] = useState('');
  useEffect(() => { setErr(''); get('/bi/commercial' + qs(f)).then(setD).catch((e) => setErr(e.message)); }, [f]);
  const labels = useMemo(() => (d ? d.timeline.map((t: any) => t.bucket) : []), [d]);
  if (!d) return <Err e={err} />; const k = d.kpis, dl = d.deltas ?? {}, g = d.goals;
  const bars = (rows: any[], badge?: (r: any) => React.ReactNode) => rows.map((r) => ({ label: r.name, value: r.revenue, sub: r.margin_pct != null ? `margem ${r.margin_pct}%` : '', badge: badge?.(r) }));
  return <><h1>BI — Comercial</h1><p className="sub">{d.definitions}</p><Err e={err} />
    <PeriodBar f={f} setF={setF} extra={<select style={{ width: 150 }} value={f.channel} onChange={(e) => setF({ ...f, channel: e.target.value })}><option value="">Todos os canais</option>{['balcao', 'atacado', 'b2b', 'externo', 'online'].map((c) => <option key={c}>{c}</option>)}</select>} />
    <div className="grid kpis" style={{ marginBottom: 14 }}><Kpi label="Faturamento" value={brl(k.revenue)} delta={dl.revenue} /><Kpi label="Vendas" value={k.orders} delta={dl.orders} /><Kpi label="Ticket médio" value={brl(k.ticket)} delta={dl.ticket} status={g.ticket ? (g.ticket.ok ? 'ok' : 'bad') : null} sub={g.ticket ? `meta ${brl(g.ticket.target)}` : undefined} />
      <Kpi label="Margem bruta" value={`${brl(k.gross_margin)} · ${pct(k.gross_margin_pct)}`} delta={dl.gross_margin} status={g.margin_pct ? (g.margin_pct.ok ? 'ok' : 'bad') : null} sub={g.margin_pct ? `meta ${g.margin_pct.target}%` : undefined} />
      <Kpi label="Margem após impostos" value={pct(k.net_margin_pct)} sub={`DAS estimado ${brl(k.tax)}`} /><Kpi label="Devoluções" value={brl(d.returns?.total ?? 0)} sub={`${d.returns?.count ?? 0} devolução(ões)${d.returns?.pct_of_revenue != null ? ` · ${pct(d.returns.pct_of_revenue)} do faturamento` : ''}`} /><Kpi label="Desconto médio" value={pct(k.discount_pct)} sub={`${k.customers} cliente(s)`} /></div>
    {g.revenue ? <div className="card" style={{ marginBottom: 14, padding: 12 }}><b>Meta de faturamento de {g.month.slice(5, 7)}/{g.month.slice(0, 4)}</b> — {brl(g.revenue.achieved)} de {brl(g.revenue.target)} ({g.revenue.pct}%) · ritmo esperado {g.revenue.expected_pct}% · projeção do mês {brl(g.revenue.projected)}
      <div style={{ background: '#f1f5f9', borderRadius: 6, height: 12, marginTop: 6, position: 'relative' }}><div style={{ width: `${Math.min(100, g.revenue.pct)}%`, height: 12, background: g.revenue.pct >= g.revenue.expected_pct ? 'var(--green)' : SERIES[1], borderRadius: 6 }} /><div title="ritmo esperado" style={{ position: 'absolute', left: `${Math.min(100, g.revenue.expected_pct)}%`, top: -3, height: 18, borderLeft: '2px solid #475569' }} /></div></div>
      : <div className="alert yellow" style={{ marginBottom: 14 }}>Meta de faturamento não definida. <Link to="/bi/metas">Definir metas</Link></div>}
    <LineChart title={`Faturamento por ${d.bucket === 'day' ? 'dia' : d.bucket === 'week' ? 'semana' : 'mês'}`} labels={labels} goal={null}
      series={[{ name: 'Período atual', values: d.timeline.map((t: any) => t.revenue) }, ...(d.comparison ? [{ name: 'Comparação', values: d.timeline.map((t: any) => t.prev_revenue), dashed: true, color: MUTED }] : [])]} />
    <div className="grid" style={{ gridTemplateColumns: 'repeat(auto-fit,minmax(420px,1fr))', marginTop: 14 }}>
      <BarList title="Vendedores (faturamento)" rows={bars(d.sellers, (r) => (r.goal_pct != null ? <span className={`pill ${r.goal_pct >= 100 ? 'green' : 'yellow'}`}>{r.goal_pct}% da meta</span> : null))} />
      <BarList title="Clientes (faturamento)" rows={d.customers.slice(0, 10).map((r: any) => ({ label: r.name, value: r.revenue, sub: `margem ${r.margin_pct}%`, badge: r.variation_pct != null ? <span className={`pill ${r.variation_pct >= 0 ? 'green' : 'red'}`}>{r.variation_pct >= 0 ? '▲' : '▼'} {Math.abs(r.variation_pct)}%</span> : null }))} />
      <BarList title="Produtos (faturamento)" rows={bars(d.products.slice(0, 10))} /><BarList title="Categorias" rows={bars(d.categories)} /><BarList title="Marcas" rows={bars(d.brands)} />
      <BarList title="Canais" rows={d.channels.map((c: any) => ({ label: c.name, value: c.revenue, sub: `${c.share_pct}% · margem ${c.margin_pct}%` }))} />{d.branches.length > 1 && <BarList title="Filiais" rows={bars(d.branches)} />}</div>
    <h2 style={{ marginTop: 24 }}>Clientes que reduziram as compras</h2><p className="muted">Queda ≥ {d.declining_customers.threshold_pct}% sobre o período de comparação, com base mínima de {brl(d.declining_customers.min_base)}.</p>
    <table><thead><tr><th>Cliente</th><th className="num">Antes</th><th className="num">Agora</th><th className="num">Variação</th><th className="num">Perda</th></tr></thead><tbody>{d.declining_customers.items.map((c: any) => <tr key={c.id}><td>{c.name}</td><td className="num">{brl(c.prev_revenue)}</td><td className="num">{brl(c.revenue)}</td><td className="num"><span className="pill red">▼ {Math.abs(c.variation_pct)}%</span></td><td className="num">{brl(c.lost)}</td></tr>)}{!d.declining_customers.items.length && <tr><td colSpan={5} className="muted">Nenhum cliente com queda relevante{d.comparison ? '' : ' (ative a comparação)'}.</td></tr>}</tbody></table>
    <h2 style={{ marginTop: 24 }}>Onde estamos perdendo margem</h2>
    <div className="grid" style={{ gridTemplateColumns: 'repeat(auto-fit,minmax(420px,1fr))' }}><div><h3>Produtos vendidos abaixo da margem mínima</h3><table><thead><tr><th>Produto</th><th className="num">Margem</th><th className="num">Mínima</th><th className="num">Faturamento</th></tr></thead><tbody>{d.margin_leaks.map((p: any) => <tr key={p.id}><td>{p.name}</td><td className="num"><span className="pill red">{p.margin_pct}%</span></td><td className="num">{p.min_margin_pct}%</td><td className="num">{brl(p.revenue)}</td></tr>)}{!d.margin_leaks.length && <tr><td colSpan={4} className="muted">Nenhum produto abaixo da margem mínima.</td></tr>}</tbody></table></div>
      <div><h3>Maiores descontos concedidos</h3><table><thead><tr><th>Produto</th><th className="num">Desconto</th><th className="num">% sobre tabela</th></tr></thead><tbody>{d.top_discounts.map((p: any) => <tr key={p.id}><td>{p.name}</td><td className="num">{brl(p.discount_value)}</td><td className="num">{pct(p.discount_pct)}</td></tr>)}{!d.top_discounts.length && <tr><td colSpan={3} className="muted">Sem descontos no período.</td></tr>}</tbody></table></div></div></>;
}

// ---------------------------------------------------------------- Estoque
export function BiStock() {
  const [d, setD] = useState<any>(null); const [err, setErr] = useState(''); useEffect(() => { get('/bi/stock').then(setD).catch((e) => setErr(e.message)); }, []); if (!d) return <Err e={err} />; const g = d.goals;
  return <><h1>BI — Estoque</h1><p className="sub">{d.definitions}</p>
    <div className="grid kpis" style={{ marginBottom: 14 }}><Kpi label="Valor em estoque" value={brl(d.stock_value)} sub={`${d.skus_in_stock} itens com saldo`} /><Kpi label="Giro anual" value={d.turnover_annual != null ? `${d.turnover_annual}x` : '—'} status={g.turnover_ok == null ? null : g.turnover_ok ? 'ok' : 'bad'} sub={g.turnover != null ? `meta ${g.turnover}x` : <Link to="/bi/metas">definir meta</Link>} />
      <Kpi label="Cobertura" value={d.coverage_days != null ? `${d.coverage_days} dias` : '—'} status={g.coverage_ok == null ? null : g.coverage_ok ? 'ok' : 'bad'} sub={g.coverage_max != null ? `máximo ${g.coverage_max} dias` : <Link to="/bi/metas">definir meta</Link>} />
      <Kpi label="Ruptura (itens)" value={d.stockouts.count} sub={`perda diária estimada ${brl(d.stockouts.est_daily_revenue_lost)}`} /><Kpi label="Excesso / sem giro" value={brl(d.excess.value)} sub={`${d.excess.count} item(ns)`} /></div>
    <div className="grid" style={{ gridTemplateColumns: 'repeat(auto-fit,minmax(420px,1fr))' }}>
      <BarList title="Curva ABC: valor em estoque por classe" rows={d.abc.map((x: any) => ({ label: `Classe ${x.class}`, value: x.stock_value, sub: `${x.products} itens · ${x.stock_share_pct}% do estoque · vendas 90 d ${brl(x.revenue_90d)}` }))} />
      <BarList title="Capital parado por tempo sem saída" rows={d.idle.map((b: any) => ({ label: `${b.bucket} dias`, value: num(b.cost_value), sub: `${b.products} itens` }))} /></div>
    <h2 style={{ marginTop: 20 }}>Por categoria</h2><table><thead><tr><th>Categoria</th><th className="num">Valor</th><th className="num">% do estoque</th><th className="num">Giro (x/ano)</th><th className="num">Cobertura (dias)</th><th className="num">Excesso</th></tr></thead><tbody>{d.categories.map((c: any) => <tr key={c.name}><td>{c.name}</td><td className="num">{brl(c.value)}</td><td className="num">{pct(c.share_pct)}</td><td className="num">{c.turnover ?? '—'} <Flag ok={c.turnover_ok} label={c.goal_turnover != null ? `meta ${c.goal_turnover}` : undefined} /></td><td className="num">{c.coverage_days ?? '—'} <Flag ok={c.coverage_ok} label={c.goal_coverage_max != null ? `máx ${c.goal_coverage_max}` : undefined} /></td><td className="num">{brl(c.excess_value)}</td></tr>)}</tbody></table>
    <div className="grid" style={{ gridTemplateColumns: 'repeat(auto-fit,minmax(420px,1fr))', marginTop: 20 }}>
      <div><h3>Ruptura: vendem e estão sem saldo</h3><table><thead><tr><th>Produto</th><th>ABC</th><th className="num">Venda/dia</th><th className="num">Perda/dia est.</th></tr></thead><tbody>{d.stockouts.items.map((x: any) => <tr key={x.id}><td>{x.name}</td><td>{x.abc}</td><td className="num">{x.avg_daily}</td><td className="num">{brl(x.est_daily_revenue_lost)}</td></tr>)}{!d.stockouts.items.length && <tr><td colSpan={4} className="muted">Sem ruptura.</td></tr>}</tbody></table></div>
      <div><h3>Maiores excessos / sem giro</h3><table><thead><tr><th>Produto</th><th className="num">Qtd</th><th className="num">Cobertura</th><th className="num">Valor</th></tr></thead><tbody>{d.excess.items.map((x: any) => <tr key={x.id}><td>{x.name}</td><td className="num">{x.qty}</td><td className="num">{x.coverage_days != null ? `${x.coverage_days} d` : 'sem venda'}</td><td className="num">{brl(x.value)}</td></tr>)}{!d.excess.items.length && <tr><td colSpan={4} className="muted">Sem excesso relevante.</td></tr>}</tbody></table></div></div></>;
}

// ---------------------------------------------------------------- Compras
export function BiPurchasing() {
  const [f, setF] = useState({ from: addDays(-89), to: today() }); const [d, setD] = useState<any>(null); const [err, setErr] = useState(''); const [p, setP] = useState<any>(null); const [ev, setEv] = useState<any>(null);
  useEffect(() => { get('/bi/purchasing' + qs(f)).then(setD).catch((e) => setErr(e.message)); }, [f]); useEffect(() => { if (p) get('/bi/purchasing/cost-evolution' + qs({ product_id: p.id })).then(setEv); else setEv(null); }, [p]); if (!d) return <Err e={err} />;
  return <><h1>BI — Compras</h1><p className="sub">{d.definitions}</p><PeriodBar f={f} setF={setF} />
    <div className="grid kpis" style={{ marginBottom: 14 }}><Kpi label="Compras no período" value={brl(d.total)} /><Kpi label="Notas de entrada" value={d.nfs} sub={`média ${brl(d.avg_nf)}`} /><Kpi label="Pedidos em aberto" value={d.open_orders.count} sub={`${brl(d.open_orders.value)} · ${d.open_orders.late} atrasado(s)`} />
      <Kpi label="A comprar agora (estimativa)" value={d.to_buy.items} sub={brl(d.to_buy.estimated)} /><Kpi label="Economia potencial" value={brl(d.savings.total)} sub="comprando do mais barato" /></div>
    <div className="grid" style={{ gridTemplateColumns: 'repeat(auto-fit,minmax(420px,1fr))' }}><BarList title="Volume por fornecedor" rows={d.suppliers.map((s: any) => ({ label: s.name, value: s.total, sub: `${s.share_pct}% · ${s.nfs} NF` }))} />
      <BarList title="Variação média de preço por fornecedor" unit="pct" rows={d.price_moves.by_supplier.map((s: any) => ({ label: s.supplier, value: Math.abs(s.avg_variation_pct), sub: `${s.avg_variation_pct > 0 ? '+' : '−'} em ${s.products} produto(s)`, color: s.avg_variation_pct > 0 ? SERIES[1] : SERIES[2] }))} /></div>
    <h2 style={{ marginTop: 20 }}>Fornecedores: prazo e pontualidade</h2><table><thead><tr><th>Fornecedor</th><th className="num">Compras</th><th className="num">Prazo de pagamento</th><th className="num">Prazo de entrega (cadastro)</th><th className="num">Prazo de entrega real</th><th className="num">Pontualidade</th></tr></thead><tbody>{d.suppliers.map((s: any) => <tr key={s.id}><td>{s.name}</td><td className="num">{brl(s.total)}</td><td className="num">{s.payment_terms_days} d</td><td className="num">{s.lead_declared_days} d</td><td className="num">{s.lead_real_days != null ? `${s.lead_real_days} d` : '—'}</td><td className="num">{s.on_time_pct != null ? <Flag ok={s.on_time_pct >= 90} label={`${s.on_time_pct}%`} /> : '—'}</td></tr>)}{!d.suppliers.length && <tr><td colSpan={6} className="muted">Sem recebimentos no período.</td></tr>}</tbody></table>
    <div className="grid" style={{ gridTemplateColumns: 'repeat(auto-fit,minmax(420px,1fr))', marginTop: 20 }}>
      <div><h3>Maiores aumentos de preço</h3><table><thead><tr><th>Produto</th><th>Fornecedor</th><th className="num">De</th><th className="num">Para</th><th className="num">%</th><th className="num">Impacto</th></tr></thead><tbody>{d.price_moves.increases.map((m: any, i: number) => <tr key={i}><td>{m.product}</td><td>{m.supplier}</td><td className="num">{brl(m.before)}</td><td className="num">{brl(m.after)}</td><td className="num"><span className="pill red">▲ {m.pct}%</span></td><td className="num">{brl(m.impact)}</td></tr>)}{!d.price_moves.increases.length && <tr><td colSpan={6} className="muted">Sem aumentos no período.</td></tr>}</tbody></table></div>
      <div><h3>Economia potencial (preço pago × melhor preço)</h3><table><thead><tr><th>Produto</th><th className="num">Pago</th><th className="num">Melhor</th><th className="num">Economia</th></tr></thead><tbody>{d.savings.items.map((m: any) => <tr key={m.id}><td>{m.name}</td><td className="num">{brl(m.avg_paid)}</td><td className="num">{brl(m.best_price)}</td><td className="num">{brl(m.potential_saving)}</td></tr>)}{!d.savings.items.length && <tr><td colSpan={4} className="muted">Nada a economizar.</td></tr>}</tbody></table></div></div>
    <h2 style={{ marginTop: 20 }}>Evolução do custo de compra (12 meses)</h2><div className="toolbar"><ProductPick value={p} onChange={setP} /></div>
    {ev && (ev.months.length > 1 ? <LineChart title={`${ev.product.sku} — preço por fornecedor`} labels={ev.months} unit="brl" series={ev.series.slice(0, 4).map((s: any, i: number) => ({ name: s.supplier, values: s.values, color: SERIES[i] }))} /> : <div className="alert yellow">Poucos pontos de preço para traçar a evolução (menos de 2 meses de histórico).</div>)}</>;
}

// ---------------------------------------------------------------- Financeiro
export function BiFinance() {
  const [d, setD] = useState<any>(null); const [err, setErr] = useState(''); useEffect(() => { get('/bi/finance').then(setD).catch((e) => setErr(e.message)); }, []); if (!d) return <Err e={err} />; const r = d.receivables;
  return <><h1>BI — Financeiro</h1><p className="sub">{d.definitions}</p>
    <div className="grid kpis" style={{ marginBottom: 14 }}><Kpi label="Caixa e bancos" value={brl(d.cash)} /><Kpi label="A receber" value={brl(r.open)} sub={r.dso_days != null ? `DSO ${r.dso_days} dias` : ''} /><Kpi label="Inadimplência" value={pct(r.delinquency_pct)} status={r.delinquency_ok == null ? null : r.delinquency_ok ? 'ok' : 'bad'} sub={r.goal_max_pct != null ? `máx. ${r.goal_max_pct}%` : <Link to="/bi/metas">definir meta</Link>} />
      <Kpi label="A pagar" value={brl(d.payables.open)} sub={d.payables.dpo_days != null ? `DPO ${d.payables.dpo_days} dias` : ''} /><Kpi label="Vencido a pagar" value={brl(d.payables.overdue)} /></div>
    <div className="grid" style={{ gridTemplateColumns: 'repeat(auto-fit,minmax(420px,1fr))' }}><BarList title="Contas a receber por faixa de atraso" rows={r.aging.map((b: any) => ({ label: b.bucket === 'a vencer' ? 'A vencer' : `Atraso ${b.bucket} d`, value: b.amount, sub: `${b.titles} título(s)`, color: b.bucket === 'a vencer' ? SERIES[0] : SERIES[1] }))} />
      <BarList title="Maiores devedores vencidos" rows={r.top_overdue.map((c: any) => ({ label: c.name, value: c.amount, sub: `${c.days} dias`, color: SERIES[1] }))} /><BarList title="Contas a pagar nas próximas semanas" rows={d.payables.next_weeks.map((w: any) => ({ label: w.week === 0 ? 'Esta semana' : `Daqui a ${w.week} sem.`, value: w.amount }))} /></div>
    <h2 style={{ marginTop: 20 }}>Resultado dos últimos meses (competência)</h2><LineChart title="Receita líquida, lucro bruto e lucro líquido" labels={d.monthly_result.map((m: any) => m.month)} series={[{ name: 'Receita líquida', values: d.monthly_result.map((m: any) => m.receita_liquida) }, { name: 'Lucro bruto', values: d.monthly_result.map((m: any) => m.lucro_bruto), color: SERIES[2] }, { name: 'Lucro líquido', values: d.monthly_result.map((m: any) => m.lucro_liquido), color: SERIES[1] }]} />
    <h2 style={{ marginTop: 20 }}>Caixa projetado</h2><table><thead><tr><th>Horizonte</th><th className="num">Saldo projetado no fim</th><th className="num">Menor saldo</th><th>Situação</th></tr></thead><tbody>{d.cashflow.map((c: any) => <tr key={c.horizon}><td>{c.horizon} dias</td><td className="num">{brl(c.ending_projected)}</td><td className="num">{brl(c.min_projected.value)}</td><td>{c.negative_from ? <span className="pill red">negativo a partir de {c.negative_from}</span> : <span className="pill green">sem saldo negativo</span>}</td></tr>)}</tbody></table><p className="muted">{d.projection.note} (confiança {d.projection.confidence})</p></>;
}

// ---------------------------------------------------------------- Metas
export function Goals() {
  const { can } = useAuth(); const [d, setD] = useState<any>(null); const [f, setF] = useState<any>({ kind: 'faturamento', scope_type: 'company', scope_id: '', month: '', target: '' }); const [users, setUsers] = useState<any[]>([]); const [cats, setCats] = useState<any[]>([]); const [err, setErr] = useState(''); const [msg, setMsg] = useState('');
  const load = () => get('/bi/goals').then(setD); useEffect(() => { load(); get('/users?is_seller=true&pageSize=100').then((r) => setUsers(r.items)).catch(() => {}); get('/categories?pageSize=200').then((r) => setCats(r.items)).catch(() => {}); }, []); if (!d) return null;
  const info = d.kinds[f.kind]; const edit = can('bi:edit');
  const save = async () => { setErr(''); setMsg(''); try { await api('PUT', '/bi/goals', { kind: f.kind, scope_type: f.scope_type, scope_id: f.scope_type === 'company' ? null : f.scope_id, month: f.month || null, target: num(f.target) }); setMsg('Meta salva.'); setF({ ...f, target: '' }); load(); } catch (e) { setErr((e as ApiError).message); } };
  const unit = (k: string) => d.kinds[k]?.unit;
  return <><h1>Metas</h1><p className="sub">Estrutura pronta: defina o valor das metas quando quiser. Sem meta definida, os painéis mostram o resultado sem comparar. Uma meta “para todos os meses” vale sempre; uma meta de um mês específico a substitui naquele mês.</p>{msg && <div className="alert green">{msg}</div>}
    {edit && <div className="card" style={{ marginBottom: 14 }}><div className="form"><div><label>Meta</label><select value={f.kind} onChange={(e) => setF({ ...f, kind: e.target.value, scope_type: 'company', scope_id: '' })}>{Object.entries(d.kinds).map(([k, v]: any) => <option key={k} value={k}>{v.label} ({v.unit})</option>)}</select></div>
      <div><label>Escopo</label><select value={f.scope_type} onChange={(e) => setF({ ...f, scope_type: e.target.value, scope_id: '' })}>{info.scopes.map((s: string) => <option key={s} value={s}>{{ company: 'Empresa toda', seller: 'Vendedor', category: 'Categoria' }[s]}</option>)}</select></div>
      {f.scope_type !== 'company' && <div><label>{f.scope_type === 'seller' ? 'Vendedor' : 'Categoria'}</label><select value={f.scope_id} onChange={(e) => setF({ ...f, scope_id: e.target.value })}><option value="">—</option>{(f.scope_type === 'seller' ? users : cats).map((x: any) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></div>}
      <div><label>Mês (vazio = todos os meses)</label><input type="month" value={f.month} onChange={(e) => setF({ ...f, month: e.target.value })} /></div><div><label>Valor da meta ({info.unit})</label><input type="number" step="0.01" value={f.target} onChange={(e) => setF({ ...f, target: e.target.value })} /></div></div>
      <p className="muted">{info.hint}</p><Err e={err} /><div className="right"><button className="primary" disabled={f.target === '' || (f.scope_type !== 'company' && !f.scope_id)} onClick={save}>Salvar meta</button></div></div>}
    <table><thead><tr><th>Meta</th><th>Escopo</th><th>Vigência</th><th className="num">Valor</th><th /></tr></thead><tbody>{d.items.map((g: any) => <tr key={g.id}><td>{d.kinds[g.kind].label}</td><td>{g.scope_type === 'company' ? 'Empresa' : `${g.scope_type === 'seller' ? 'Vendedor' : 'Categoria'}: ${g.scope_name}`}</td><td>{g.month ? `${g.month.slice(5, 7)}/${g.month.slice(0, 4)}` : 'todos os meses'}</td><td className="num">{unit(g.kind) === 'R$' ? brl(g.target) : `${num(g.target).toLocaleString('pt-BR')} ${unit(g.kind)}`}</td>
      <td>{can('bi:delete') && <button className="danger" onClick={() => api('DELETE', `/bi/goals/${g.id}`).then(load)}>remover</button>}</td></tr>)}{!d.items.length && <tr><td colSpan={5} className="muted">Nenhuma meta definida ainda.</td></tr>}</tbody></table></>;
}
void fmt;
