import { useEffect, useMemo, useRef, useState } from 'react';
import { api, ApiError, brl, get, pct, qs } from './api';
import { useAuth } from './auth';
import { CustomerPicker } from './commercial';
import { Modal } from './DataPage';
import { WhatsAppButton } from './share';

const date = (v: any) => (v ? String(v).slice(0, 10).split('-').reverse().join('/') : '—');
const num = (v: any) => Number(v ?? 0);
const COLOR: Record<string, string> = { pago: 'green', aberto: 'yellow', parcial: 'yellow', cancelado: 'gray', estornado: 'gray', pendente: 'yellow', conciliado: 'green', ignorado: 'gray' };
const Tag = ({ s }: { s: string }) => <span className={`pill ${COLOR[s] ?? 'gray'}`}>{s}</span>;
const Err = ({ e }: { e: string }) => (e ? <div className="err">{e}</div> : null);
const input = (v: any, set: (s: string) => void, p: Record<string, any> = {}) => <input value={v ?? ''} onChange={(e) => set(e.target.value)} {...p} />;

function useAccounts() { const [l, setL] = useState<any[]>([]); const load = () => get('/bank-accounts').then((r) => setL(r.items)); useEffect(() => { load(); }, []); return { accounts: l, reload: load }; }
function AccountSelect({ value, onChange, kinds, width = 260 }: { value: string; onChange: (v: string) => void; kinds?: string[]; width?: number }) {
  const { accounts } = useAccounts(); return <select style={{ width }} value={value} onChange={(e) => onChange(e.target.value)}><option value="">Conta…</option>{accounts.filter((a) => a.active && (!kinds || kinds.includes(a.kind))).map((a) => <option key={a.id} value={a.id}>{a.name} ({brl(a.balance)})</option>)}</select>;
}

// ---------------------------------------------------------------- Baixa (recebimento/pagamento)
function SettleModal({ kind, id, onClose, onDone }: { kind: 'receivable' | 'payable'; id: string; onClose(): void; onDone(): void }) {
  const base = kind === 'receivable' ? 'receivables' : 'payables'; const { can } = useAuth();
  const [t, setT] = useState<any>(null); const [f, setF] = useState<any>({ date: new Date().toISOString().slice(0, 10), account_id: '', principal: '', discount: '', interest: '', fine: '', fee: '' }); const [ch, setCh] = useState<any>(null); const [err, setErr] = useState('');
  useEffect(() => { get(`/${base}/${id}`).then((x) => { setT(x); setF((p: any) => ({ ...p, principal: String(x.outstanding) })); }); }, [id]);
  useEffect(() => { if (t) get(`/${base}/${id}/charges?date=${f.date}`).then((c) => { setCh(c); setF((p: any) => ({ ...p, interest: String(num(c.interest) * Math.min(1, num(p.principal) / Math.max(0.01, num(c.outstanding)))), fine: String(c.fine) })); }); }, [t, f.date]);
  useEffect(() => { if (ch) setF((p: any) => ({ ...p, interest: (num(ch.interest) * Math.min(1, num(p.principal) / Math.max(0.01, num(ch.outstanding)))).toFixed(2) })); }, [f.principal]);
  if (!t) return null;
  const cash = num(f.principal) - num(f.discount) + num(f.interest) + num(f.fine) - num(f.fee);
  const save = async () => { setErr(''); try { await api('POST', `/${base}/${id}/settle`, { date: f.date, account_id: f.account_id, principal: num(f.principal), discount: num(f.discount), interest: num(f.interest), fine: num(f.fine), ...(kind === 'receivable' ? { fee: num(f.fee) } : {}) }); onDone(); } catch (e) { setErr((e as ApiError).message); } };
  return <Modal onClose={onClose}><h2 style={{ marginTop: 0 }}>{kind === 'receivable' ? 'Receber' : 'Pagar'} — {t.description ?? t.customer_name ?? t.supplier_name}</h2>
    <p className="muted">Vencimento {date(t.due_date)} · valor {brl(t.amount)} · saldo em aberto <b>{brl(t.outstanding)}</b>{ch?.days_late > 0 && <> · <span className="pill red">{ch.days_late} dia(s) de atraso</span></>}</p>
    {ch && ch.total > 0 && <div className="alert yellow">Encargos pelo padrão da empresa (multa {ch.policy.fine_pct}% única + juros {ch.policy.interest_monthly_pct}% a.m. pro rata): multa {brl(ch.fine)} + juros {brl(ch.interest)}.{kind === 'receivable' && !can('finance:approve') && ' Para perdoar encargos é preciso aprovação de gestor.'}</div>}
    <div className="form"><div><label>Data</label>{input(f.date, (v) => setF({ ...f, date: v }), { type: 'date' })}</div><div><label>Conta *</label><AccountSelect value={f.account_id} onChange={(v) => setF({ ...f, account_id: v })} width={9999} /></div>
      <div><label>Valor do título quitado</label>{input(f.principal, (v) => setF({ ...f, principal: v }), { type: 'number', step: '0.01' })}</div><div><label>Desconto</label>{input(f.discount, (v) => setF({ ...f, discount: v }), { type: 'number', step: '0.01' })}</div>
      <div><label>Juros</label>{input(f.interest, (v) => setF({ ...f, interest: v }), { type: 'number', step: '0.01' })}</div><div><label>Multa</label>{input(f.fine, (v) => setF({ ...f, fine: v }), { type: 'number', step: '0.01' })}</div>
      {kind === 'receivable' && <div><label>Taxa de cartão/gateway</label>{input(f.fee, (v) => setF({ ...f, fee: v }), { type: 'number', step: '0.01' })}</div>}</div>
    <p style={{ textAlign: 'right' }}>{kind === 'receivable' ? 'Entra' : 'Sai'} na conta: <b style={{ fontSize: 20 }}>{brl(cash)}</b></p><Err e={err} />
    <div className="right"><button onClick={onClose}>Cancelar</button><button className="primary" disabled={!f.account_id || cash < 0} onClick={save}>Confirmar {kind === 'receivable' ? 'recebimento' : 'pagamento'}</button></div></Modal>;
}

function TitleDetail({ kind, id, onClose }: { kind: 'receivable' | 'payable'; id: string; onClose(): void }) {
  const base = kind === 'receivable' ? 'receivables' : 'payables'; const { can } = useAuth(); const [t, setT] = useState<any>(null); const [err, setErr] = useState(''); const [settle, setSettle] = useState(false); const [credit, setCredit] = useState<any>(null);
  const load = () => get(`/${base}/${id}`).then(setT); useEffect(() => { load(); }, [id]); if (!t) return null;
  const run = async (fn: () => Promise<any>) => { setErr(''); try { await fn(); await load(); } catch (e) { setErr((e as ApiError).message); } };
  const open = ['aberto', 'parcial'].includes(t.status);
  return <Modal onClose={onClose}><h2 style={{ marginTop: 0 }}>{t.description ?? (kind === 'receivable' ? 'Título a receber' : 'Título a pagar')} <Tag s={t.status} />{t.kind === 'credito' && <span className="pill gray" style={{ marginLeft: 6 }}>crédito</span>}</h2>
    <p className="muted">{t.customer_name ?? t.supplier_name ?? t.payee_name ?? ''} · vencimento {date(t.due_date)} · parcela {t.installment_no}/{t.installments} · valor {brl(t.amount)} · saldo {brl(t.outstanding)} · {t.category_name ?? ''} {t.cost_center_name ? '· ' + t.cost_center_name : ''} · competência {date(t.competence)}</p>
    <b>Baixas</b><table><thead><tr><th>Data</th><th>Conta</th><th className="num">Principal</th><th className="num">Desc.</th><th className="num">Juros</th><th className="num">Multa</th><th className="num">Taxa</th><th /></tr></thead><tbody>
      {t.settlements.map((s: any) => <tr key={s.id} style={s.reversed_at ? { opacity: 0.5, textDecoration: 'line-through' } : {}}><td>{date(s.settle_date)}</td><td>{s.account_name ?? s.method}</td><td className="num">{brl(s.principal)}</td><td className="num">{brl(s.discount)}</td><td className="num">{brl(s.interest)}</td><td className="num">{brl(s.fine)}</td><td className="num">{brl(s.fee)}</td>
        <td>{!s.reversed_at && can('finance:approve') && <button className="danger" onClick={() => confirm('Estornar esta baixa?') && run(() => api('POST', `/settlements/${s.id}/reverse`))}>estornar</button>}</td></tr>)}
      {!t.settlements.length && <tr><td colSpan={8} className="muted">Sem baixas.</td></tr>}</tbody></table>
    <Err e={err} />
    <div className="right">{open && kind === 'receivable' && t.customer_id && <WhatsAppButton kind="receivable" id={id} label={t.overdue || String(t.due_date).slice(0, 10) < new Date().toISOString().slice(0, 10) ? 'Cobrar por WhatsApp' : 'Lembrete por WhatsApp'} />}{open && kind === 'payable' && t.kind === 'titulo' && t.supplier_id && can('finance:edit') && <button onClick={async () => { const cr = await get('/payables' + qs({ kind: 'credito', supplier_id: t.supplier_id, status: 'aberto' })); if (!cr.items.length) return setErr('Fornecedor sem créditos em aberto.'); setCredit(cr.items[0]); }}>Compensar crédito</button>}
      {open && t.kind !== 'credito' && can('finance:delete') && !t.sale_id && !t.receiving_id && <button className="danger" onClick={() => { const reason = prompt('Motivo do cancelamento:'); if (reason) run(() => api('POST', `/${base}/${id}/cancel`, { reason })); }}>Cancelar título</button>}
      {open && t.kind !== 'credito' && can('finance:edit') && <button className="primary" onClick={() => setSettle(true)}>{kind === 'receivable' ? 'Receber' : 'Pagar'}</button>}<button onClick={onClose}>Fechar</button></div>
    {settle && <SettleModal kind={kind} id={id} onClose={() => setSettle(false)} onDone={() => { setSettle(false); load(); }} />}
    {credit && <Modal onClose={() => setCredit(null)}><h3 style={{ marginTop: 0 }}>Compensar crédito</h3><p>{credit.description} — saldo {brl(credit.outstanding)}</p><button className="primary" onClick={() => run(() => api('POST', `/payables/${id}/apply-credit`, { credit_id: credit.id, amount: Math.min(num(credit.outstanding), num(t.outstanding)) })).then(() => setCredit(null))}>Aplicar {brl(Math.min(num(credit.outstanding), num(t.outstanding)))}</button></Modal>}</Modal>;
}

function Titles({ kind }: { kind: 'receivable' | 'payable' }) {
  const { can } = useAuth(); const base = kind === 'receivable' ? 'receivables' : 'payables'; const [status, setStatus] = useState('aberto'); const [overdue, setOverdue] = useState(false); const [q, setQ] = useState(''); const [d, setD] = useState<any>({ items: [] });
  const [open, setOpen] = useState<string | null>(null); const [creating, setCreating] = useState(false); const [aging, setAging] = useState<any>(null);
  const load = () => get(`/${base}` + qs({ status, overdue: overdue || '', q, pageSize: 100 })).then(setD); useEffect(() => { const t = setTimeout(load, 200); return () => clearTimeout(t); }, [status, overdue, q]);
  useEffect(() => { if (kind === 'receivable') get('/receivables/aging').then(setAging); }, []);
  return <><h1>{kind === 'receivable' ? 'Contas a receber' : 'Contas a pagar'}</h1><p className="sub">{kind === 'receivable' ? 'Parcelas das vendas e títulos avulsos. Baixa total ou parcial com juros e multa pelo padrão da empresa.' : 'Notas de compra, despesas e comissões, com categoria, centro de custo e competência.'}</p>
    <div className="grid kpis" style={{ marginBottom: 12 }}><div className="card kpi"><div className="v">{brl(d.open_amount)}</div><div className="l">Em aberto</div></div><div className="card kpi"><div className="v" style={{ color: num(d.overdue_amount) > 0 ? 'var(--red)' : undefined }}>{brl(d.overdue_amount)}</div><div className="l">Vencido</div></div>
      {kind === 'payable' && <div className="card kpi"><div className="v">{brl(d.credit_amount)}</div><div className="l">Créditos de fornecedores a abater</div></div>}
      {aging?.buckets.map((b: any) => <div key={b.bucket} className="card kpi"><div className="v" style={{ fontSize: 18 }}>{brl(b.amount)}</div><div className="l">{b.bucket === 'a vencer' ? 'A vencer' : `Atraso ${b.bucket} d`} ({b.titles})</div></div>)}</div>
    <div className="toolbar"><input placeholder="Pesquisar…" value={q} onChange={(e) => setQ(e.target.value)} /><select style={{ width: 160 }} value={status} onChange={(e) => setStatus(e.target.value)}><option value="aberto">Em aberto</option><option value="pago">Pagos</option><option value="cancelado">Cancelados</option><option value="">Todos</option></select>
      <label className="chk" style={{ margin: 0 }}><input type="checkbox" checked={overdue} onChange={(e) => setOverdue(e.target.checked)} />somente vencidos</label><span style={{ flex: 1 }} />{can('finance:create') && <button className="primary" onClick={() => setCreating(true)}>+ {kind === 'receivable' ? 'Novo título' : 'Nova despesa'}</button>}</div>
    <table><thead><tr><th>Vencimento</th><th>{kind === 'receivable' ? 'Cliente' : 'Fornecedor / beneficiário'}</th><th>Descrição</th><th>Parcela</th><th className="num">Valor</th><th className="num">Saldo</th><th>Status</th></tr></thead><tbody>
      {d.items.map((t: any) => <tr key={t.id} className="click" onClick={() => setOpen(t.id)}><td>{date(t.due_date)} {t.overdue && <span className="pill red">{t.days_late ?? ''} atraso</span>}</td><td>{t.customer_name ?? t.supplier_name ?? t.payee_name ?? <span className="muted">—</span>}</td><td>{t.description}{t.kind === 'credito' && <span className="pill gray" style={{ marginLeft: 6 }}>crédito</span>}</td><td>{t.installment_no}/{t.installments}</td><td className="num">{brl(t.amount)}</td><td className="num">{brl(t.outstanding)}</td><td><Tag s={t.status} /></td></tr>)}
      {!d.items.length && <tr><td colSpan={7} className="muted">Nenhum título.</td></tr>}</tbody></table>
    {open && <TitleDetail kind={kind} id={open} onClose={() => { setOpen(null); load(); }} />}{creating && (kind === 'receivable' ? <NewReceivable onClose={() => setCreating(false)} onDone={() => { setCreating(false); load(); }} /> : <NewPayable onClose={() => setCreating(false)} onDone={() => { setCreating(false); load(); }} />)}</>;
}
export const Receivables = () => <Titles kind="receivable" />;
export const Payables = () => <Titles kind="payable" />;

function NewReceivable({ onClose, onDone }: { onClose(): void; onDone(): void }) {
  const [c, setC] = useState<any>(null); const [f, setF] = useState({ due_date: '', amount: '', description: '' }); const [err, setErr] = useState('');
  return <Modal onClose={onClose}><h2 style={{ marginTop: 0 }}>Novo título a receber</h2><div className="form"><div className="full"><label>Cliente (opcional)</label><CustomerPicker value={c} onChange={setC} /></div><div><label>Vencimento *</label>{input(f.due_date, (v) => setF({ ...f, due_date: v }), { type: 'date' })}</div><div><label>Valor *</label>{input(f.amount, (v) => setF({ ...f, amount: v }), { type: 'number', step: '0.01' })}</div><div className="full"><label>Descrição *</label>{input(f.description, (v) => setF({ ...f, description: v }))}</div></div>
    <Err e={err} /><div className="right"><button onClick={onClose}>Cancelar</button><button className="primary" disabled={!f.due_date || !f.amount || f.description.length < 3} onClick={() => api('POST', '/receivables', { customer_id: c?.id ?? null, due_date: f.due_date, amount: num(f.amount), description: f.description }).then(onDone).catch((e) => setErr(e.message))}>Salvar</button></div></Modal>;
}
function NewPayable({ onClose, onDone }: { onClose(): void; onDone(): void }) {
  const [cats, setCats] = useState<any[]>([]); const [ccs, setCcs] = useState<any[]>([]); const [sups, setSups] = useState<any[]>([]); const [err, setErr] = useState('');
  const [f, setF] = useState<any>({ description: '', category_id: '', cost_center_id: '', supplier_id: '', first_due_date: '', amount: '', installments: '1', repeat_monthly: false, doc_number: '' });
  useEffect(() => { get('/finance/categories').then((r) => setCats(r.items.filter((c: any) => c.kind !== 'receita'))); get('/finance/cost-centers').then((r) => setCcs(r.items)); get('/suppliers?pageSize=200').then((r) => setSups(r.items)); }, []);
  const sel = (k: string, items: any[], label: string, val = 'id', txt = 'name') => <div><label>{label}</label><select value={f[k]} onChange={(e) => setF({ ...f, [k]: e.target.value })}><option value="">—</option>{items.map((i) => <option key={i[val]} value={i[val]}>{i[txt]}</option>)}</select></div>;
  return <Modal onClose={onClose}><h2 style={{ marginTop: 0 }}>Nova despesa / conta a pagar</h2><div className="form"><div className="full"><label>Descrição *</label>{input(f.description, (v) => setF({ ...f, description: v }))}</div>{sel('category_id', cats, 'Categoria *')}{sel('cost_center_id', ccs, 'Centro de custo')}{sel('supplier_id', sups, 'Fornecedor', 'id', 'legal_name')}
    <div><label>1º vencimento *</label>{input(f.first_due_date, (v) => setF({ ...f, first_due_date: v }), { type: 'date' })}</div><div><label>{f.repeat_monthly ? 'Valor mensal *' : 'Valor total *'}</label>{input(f.amount, (v) => setF({ ...f, amount: v }), { type: 'number', step: '0.01' })}</div><div><label>Parcelas / meses</label>{input(f.installments, (v) => setF({ ...f, installments: v }), { type: 'number', min: 1 })}</div><div><label>Documento</label>{input(f.doc_number, (v) => setF({ ...f, doc_number: v }))}</div>
    <label className="chk"><input type="checkbox" checked={f.repeat_monthly} onChange={(e) => setF({ ...f, repeat_monthly: e.target.checked })} />Despesa recorrente (repete o mesmo valor todo mês)</label></div><Err e={err} />
    <div className="right"><button onClick={onClose}>Cancelar</button><button className="primary" disabled={!f.category_id || !f.first_due_date || !f.amount || f.description.length < 3} onClick={() => api('POST', '/payables', { description: f.description, category_id: f.category_id, cost_center_id: f.cost_center_id || null, supplier_id: f.supplier_id || null, first_due_date: f.first_due_date, amount: num(f.amount), installments: num(f.installments) || 1, repeat_monthly: f.repeat_monthly, doc_number: f.doc_number || null }).then(onDone).catch((e) => setErr(e.message))}>Salvar</button></div></Modal>;
}

// ---------------------------------------------------------------- Bancos e caixa
export function Banks() {
  const { can } = useAuth(); const { accounts, reload } = useAccounts(); const [sel, setSel] = useState<any>(null); const [st, setSt] = useState<any>(null); const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [modal, setModal] = useState<string | null>(null); const [sessions, setSessions] = useState<any[]>([]);
  const loadSt = () => sel && get(`/bank-accounts/${sel.id}/statement` + qs({ from, to })).then(setSt); useEffect(() => { loadSt(); }, [sel, from, to]);
  const loadSessions = () => get('/cash/sessions').then((r) => setSessions(r.items)); useEffect(() => { loadSessions(); }, []);
  const total = accounts.filter((a) => a.active && a.kind !== 'aplicacao').reduce((s, a) => s + num(a.balance), 0);
  return <><h1>Bancos e caixa</h1><p className="sub">Saldo = saldo inicial + movimentos. Saldo disponível (bancos + caixa): <b>{brl(total)}</b>. O caixa físico é opcional.</p>
    <div className="toolbar"><span style={{ flex: 1 }} />{can('finance:create') && <><button onClick={() => setModal('transfer')}>Transferir / aplicar</button><button onClick={() => setModal('movement')}>Lançamento avulso</button><button className="primary" onClick={() => setModal('account')}>+ Conta</button></>}</div>
    <div className="grid kpis">{accounts.map((a) => <div key={a.id} className="card kpi click" style={{ cursor: 'pointer', outline: sel?.id === a.id ? '2px solid var(--blue-600)' : undefined, opacity: a.active ? 1 : 0.5 }} onClick={() => setSel(a)}><div className="v">{brl(a.balance)}</div><div className="l">{a.name} · {a.kind}</div>{a.pending_lines > 0 && <span className="pill yellow">{a.pending_lines} a conciliar</span>}</div>)}</div>
    {sel && st && <><h3>Extrato do ERP — {sel.name}</h3><div className="toolbar"><input type="date" style={{ maxWidth: 160 }} value={from} onChange={(e) => setFrom(e.target.value)} /><input type="date" style={{ maxWidth: 160 }} value={to} onChange={(e) => setTo(e.target.value)} /><span className="muted">saldo anterior {brl(st.opening)} · saldo final {brl(st.closing)}</span></div>
      <table><thead><tr><th>Data</th><th>Tipo</th><th>Descrição</th><th>Categoria</th><th className="num">Valor</th><th className="num">Saldo</th><th>Conciliação</th></tr></thead><tbody>
        {st.items.map((m: any) => <tr key={m.id} style={m.reversed ? { opacity: 0.5, textDecoration: 'line-through' } : {}}><td>{date(m.movement_date)}</td><td>{m.kind}</td><td>{m.description}</td><td>{m.category_name}</td><td className="num" style={{ color: num(m.amount) < 0 ? 'var(--red)' : 'var(--green)' }}>{brl(m.amount)}</td><td className="num">{brl(m.balance)}</td><td>{m.recon ? <Tag s={m.recon} /> : <span className="muted">—</span>}</td></tr>)}</tbody></table></>}
    <h3 style={{ marginTop: 28 }}>Caixa físico</h3>
    <div className="toolbar">{can('finance:create') && <button onClick={() => setModal('cash-open')}>Abrir caixa</button>}<span className="muted">Sem balcão na operação atual: use apenas se houver dinheiro em espécie a controlar.</span></div>
    <table><thead><tr><th>Abertura</th><th>Conta</th><th>Operador</th><th className="num">Abertura</th><th className="num">Esperado</th><th className="num">Contado</th><th className="num">Diferença</th><th>Status</th><th /></tr></thead><tbody>
      {sessions.map((s) => <tr key={s.id}><td>{new Date(s.opened_at).toLocaleString('pt-BR')}</td><td>{s.account_name}</td><td>{s.opened_by_name}</td><td className="num">{brl(s.opening_amount)}</td><td className="num">{brl(s.expected_now)}</td><td className="num">{s.counted_amount != null ? brl(s.counted_amount) : '—'}</td><td className="num">{s.difference != null ? brl(s.difference) : '—'}</td><td><Tag s={s.status === 'aberto' ? 'aberto' : 'pago'} /></td>
        <td>{s.status === 'aberto' && can('finance:create') && <><button onClick={() => setModal('cash-mov:' + s.id)}>sangria/suprimento</button> <button className="primary" onClick={() => setModal('cash-close:' + s.id)}>fechar</button></>}</td></tr>)}</tbody></table>
    {modal && <BankModals modal={modal} accounts={accounts} onClose={() => setModal(null)} onDone={() => { setModal(null); reload(); loadSt(); loadSessions(); }} />}</>;
}
function BankModals({ modal, accounts, onClose, onDone }: { modal: string; accounts: any[]; onClose(): void; onDone(): void }) {
  const [f, setF] = useState<any>({ kind: modal === 'transfer' ? 'transferencia' : 'tarifa', type: 'sangria' }); const [err, setErr] = useState(''); const [cats, setCats] = useState<any[]>([]);
  useEffect(() => { if (modal === 'movement') get('/finance/categories').then((r) => setCats(r.items)); }, []);
  const [name, id] = modal.split(':'); const set = (k: string) => (v: string) => setF({ ...f, [k]: v });
  const acc = (k: string, label: string, kinds?: string[]) => <div><label>{label}</label><select value={f[k] ?? ''} onChange={(e) => set(k)(e.target.value)}><option value="">—</option>{accounts.filter((a) => a.active && (!kinds || kinds.includes(a.kind))).map((a) => <option key={a.id} value={a.id}>{a.name}</option>)}</select></div>;
  const go = async (fn: () => Promise<any>) => { setErr(''); try { await fn(); onDone(); } catch (e) { setErr((e as ApiError).message); } };
  const body = name === 'account' ? <><div className="form"><div className="full"><label>Nome *</label>{input(f.name, set('name'))}</div><div><label>Tipo</label><select value={f.k ?? 'banco'} onChange={(e) => set('k')(e.target.value)}><option value="banco">Banco</option><option value="caixa">Caixa</option><option value="aplicacao">Aplicação</option></select></div><div><label>Banco</label>{input(f.bank_name, set('bank_name'))}</div><div><label>Agência</label>{input(f.agency, set('agency'))}</div><div><label>Conta</label>{input(f.account_number, set('account_number'))}</div><div><label>Saldo inicial</label>{input(f.opening_balance, set('opening_balance'), { type: 'number', step: '0.01' })}</div><div><label>Data do saldo</label>{input(f.opening_date, set('opening_date'), { type: 'date' })}</div></div>
      <div className="right"><button onClick={onClose}>Cancelar</button><button className="primary" disabled={!f.name} onClick={() => go(() => api('POST', '/bank-accounts', { name: f.name, kind: f.k ?? 'banco', bank_name: f.bank_name || null, agency: f.agency || null, account_number: f.account_number || null, opening_balance: num(f.opening_balance), opening_date: f.opening_date || undefined }))}>Criar</button></div></>
    : name === 'transfer' ? <><div className="form">{acc('from', 'Origem')}{acc('to', 'Destino')}<div><label>Valor</label>{input(f.amount, set('amount'), { type: 'number', step: '0.01' })}</div><div><label>Tipo</label><select value={f.kind} onChange={(e) => set('kind')(e.target.value)}><option value="transferencia">Transferência</option><option value="aplicacao">Aplicação</option><option value="resgate">Resgate</option></select></div><div><label>Data</label>{input(f.date, set('date'), { type: 'date' })}</div><div className="full"><label>Descrição</label>{input(f.description, set('description'))}</div></div>
      <div className="right"><button onClick={onClose}>Cancelar</button><button className="primary" disabled={!f.from || !f.to || !f.amount} onClick={() => go(() => api('POST', '/bank-accounts/transfer', { from_account_id: f.from, to_account_id: f.to, amount: num(f.amount), kind: f.kind, date: f.date || undefined, description: f.description || null }))}>Confirmar</button></div></>
    : name === 'movement' ? <><div className="form">{acc('account', 'Conta')}<div><label>Tipo</label><select value={f.kind} onChange={(e) => set('kind')(e.target.value)}><option value="tarifa">Tarifa</option><option value="juros">Juros</option><option value="rendimento">Rendimento</option><option value="ajuste">Ajuste (gestor)</option></select></div><div><label>Valor (− saída, + entrada)</label>{input(f.amount, set('amount'), { type: 'number', step: '0.01' })}</div><div><label>Data</label>{input(f.date, set('date'), { type: 'date' })}</div>
      <div><label>Categoria</label><select value={f.category_id ?? ''} onChange={(e) => set('category_id')(e.target.value)}><option value="">Padrão do tipo</option>{cats.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="full"><label>Descrição *</label>{input(f.description, set('description'))}</div></div>
      <div className="right"><button onClick={onClose}>Cancelar</button><button className="primary" disabled={!f.account || !f.amount || (f.description ?? '').length < 3} onClick={() => go(() => api('POST', '/account-movements', { account_id: f.account, kind: f.kind, amount: num(f.amount), date: f.date || undefined, category_id: f.category_id || null, description: f.description }))}>Lançar</button></div></>
    : name === 'cash-open' ? <><div className="form">{acc('account', 'Conta caixa', ['caixa'])}<div><label>Valor de abertura</label>{input(f.opening, set('opening'), { type: 'number', step: '0.01' })}</div></div><div className="right"><button onClick={onClose}>Cancelar</button><button className="primary" disabled={!f.account} onClick={() => go(() => api('POST', '/cash/open', { account_id: f.account, opening_amount: num(f.opening) }))}>Abrir</button></div></>
    : name === 'cash-mov' ? <><div className="form"><div><label>Tipo</label><select value={f.type} onChange={(e) => set('type')(e.target.value)}><option value="sangria">Sangria (retirada)</option><option value="suprimento">Suprimento (reforço)</option></select></div><div><label>Valor</label>{input(f.amount, set('amount'), { type: 'number', step: '0.01' })}</div>{acc('other', f.type === 'sangria' ? 'Destino (opcional)' : 'Origem (opcional)')}<div className="full"><label>Motivo *</label>{input(f.note, set('note'))}</div></div><div className="right"><button onClick={onClose}>Cancelar</button><button className="primary" disabled={!f.amount || (f.note ?? '').length < 3} onClick={() => go(() => api('POST', `/cash/${id}/movement`, { type: f.type, amount: num(f.amount), other_account_id: f.other || null, note: f.note }))}>Registrar</button></div></>
    : <><div className="form"><div><label>Valor contado no caixa *</label>{input(f.counted, set('counted'), { type: 'number', step: '0.01' })}</div><div className="full"><label>Observação</label>{input(f.note, set('note'))}</div></div><div className="right"><button onClick={onClose}>Cancelar</button><button className="primary" disabled={f.counted == null || f.counted === ''} onClick={() => go(async () => { const r = await api('POST', `/cash/${id}/close`, { counted_amount: num(f.counted), note: f.note || null }); alert(`Esperado ${brl(r.expected)} · contado ${brl(r.counted)} · diferença ${brl(r.difference)}`); })}>Fechar caixa</button></div></>;
  return <Modal onClose={onClose}><h2 style={{ marginTop: 0 }}>{{ account: 'Nova conta', transfer: 'Transferir / aplicar', movement: 'Lançamento avulso', 'cash-open': 'Abrir caixa', 'cash-mov': 'Sangria / suprimento', 'cash-close': 'Fechar caixa' }[name]}</h2>{body}<Err e={err} /></Modal>;
}

// ---------------------------------------------------------------- Conciliação
export function Reconciliation() {
  const { can } = useAuth(); const [acc, setAcc] = useState(''); const [status, setStatus] = useState('pendente'); const [d, setD] = useState<any>({ items: [] }); const [sum, setSum] = useState<any>(null); const [imp, setImp] = useState<any>(null); const [line, setLine] = useState<any>(null); const [msg, setMsg] = useState(''); const file = useRef<HTMLInputElement>(null); const [enc, setEnc] = useState('utf-8');
  const load = () => { if (!acc) return; get('/reconciliation/lines' + qs({ account_id: acc, status, pageSize: 200 })).then(setD); get('/reconciliation/summary' + qs({ account_id: acc })).then(setSum); }; useEffect(() => { load(); }, [acc, status]);
  const pick = async (f: File) => { const csv = new TextDecoder(enc).decode(await f.arrayBuffer()); const pv = await api('POST', `/bank-accounts/${acc}/statement/preview`, { csv }); setImp({ csv, pv, mapping: pv.mapping }); };
  const remap = async (m: any) => { const pv = await api('POST', `/bank-accounts/${acc}/statement/preview`, { csv: imp.csv, mapping: m }); setImp({ ...imp, pv, mapping: m }); };
  return <><h1>Conciliação bancária</h1><p className="sub">Importe o extrato em CSV, concilie automaticamente com os movimentos do ERP e resolva o restante: baixar título, lançar tarifa/rendimento ou ignorar.</p>
    {msg && <div className="alert green">{msg}</div>}
    <div className="toolbar"><AccountSelect value={acc} onChange={setAcc} kinds={['banco', 'aplicacao']} />{acc && can('finance:create') && <><input ref={file} type="file" accept=".csv,.txt,text/csv" style={{ display: 'none' }} onChange={(e) => { const f = e.target.files?.[0]; if (f) pick(f).catch((x) => setMsg(x.message)); e.target.value = ''; }} />
      <select style={{ width: 150 }} value={enc} onChange={(e) => setEnc(e.target.value)} title="Codificação do arquivo"><option value="utf-8">UTF-8</option><option value="iso-8859-1">ISO-8859-1 (Latin-1)</option></select><button className="primary" onClick={() => file.current?.click()}>Importar extrato CSV</button><button onClick={() => api('POST', '/reconciliation/auto', { account_id: acc }).then((r) => { setMsg(`${r.matched} linha(s) conciliada(s) automaticamente.`); load(); })}>Conciliar automático</button></>}</div>
    {sum && <div className="grid kpis" style={{ marginBottom: 12 }}>{[['Pendentes', sum.pending], ['Conciliadas', sum.reconciled], ['Ignoradas', sum.ignored], ['Saldo ERP', brl(sum.erp_balance)], ['Mov. ERP sem extrato', `${sum.unreconciled_movements} (${brl(sum.unreconciled_movements_amount)})`]].map(([l, v]) => <div key={l as string} className="card kpi"><div className="v" style={{ fontSize: 20 }}>{v}</div><div className="l">{l}</div></div>)}</div>}
    {acc && <><div className="toolbar"><select style={{ width: 160 }} value={status} onChange={(e) => setStatus(e.target.value)}><option value="pendente">Pendentes</option><option value="conciliado">Conciliadas</option><option value="ignorado">Ignoradas</option><option value="">Todas</option></select></div>
      <table><thead><tr><th>Data</th><th>Histórico</th><th>Doc.</th><th className="num">Valor</th><th>Status</th><th /></tr></thead><tbody>
        {d.items.map((l: any) => <tr key={l.id}><td>{date(l.line_date)}</td><td>{l.description}{l.note && <div className="muted">{l.note}</div>}</td><td>{l.doc_ref}</td><td className="num" style={{ color: num(l.amount) < 0 ? 'var(--red)' : 'var(--green)' }}>{brl(l.amount)}</td><td><Tag s={l.status} /></td>
          <td>{l.status === 'pendente' && can('finance:edit') && <button className="primary" onClick={() => setLine(l)}>conciliar</button>}{l.status !== 'pendente' && can('finance:approve') && <button onClick={() => api('POST', `/reconciliation/lines/${l.id}/undo`).then(load)}>desfazer</button>}</td></tr>)}
        {!d.items.length && <tr><td colSpan={6} className="muted">Nenhuma linha.</td></tr>}</tbody></table></>}
    {imp && <ImportModal imp={imp} remap={remap} onClose={() => setImp(null)} onImport={async (save) => { const r = await api('POST', `/bank-accounts/${acc}/statement/import`, { csv: imp.csv, mapping: imp.mapping, save_profile: save }); setMsg(`Importadas ${r.inserted} linhas (${r.duplicates} já existiam, ${r.skipped} ignoradas). Conciliação automática: ${r.auto_reconciled}.`); setImp(null); load(); }} />}
    {line && <LineModal line={line} onClose={() => setLine(null)} onDone={() => { setLine(null); load(); }} />}</>;
}
function ImportModal({ imp, remap, onClose, onImport }: { imp: any; remap: (m: any) => Promise<void>; onClose(): void; onImport: (save: boolean) => Promise<void> }) {
  const { pv, mapping } = imp; const [save, setSave] = useState(true); const [err, setErr] = useState(''); const cols: string[] = pv.headers?.length ? pv.headers : pv.sample_rows?.[0] ?? [];
  const col = (k: string, label: string) => <div><label>{label}</label><select value={mapping?.[k] ?? ''} onChange={(e) => remap({ ...(mapping ?? { date: 0, header_row: 0 }), [k]: e.target.value === '' ? undefined : Number(e.target.value) })}><option value="">—</option>{cols.map((c, i) => <option key={i} value={i}>{i + 1}. {c}</option>)}</select></div>;
  return <Modal onClose={onClose}><h2 style={{ marginTop: 0 }}>Importar extrato CSV</h2>
    <div className={`alert ${pv.guessed ? 'yellow' : 'green'}`}>{mapping ? (pv.guessed ? 'Colunas detectadas automaticamente pelo cabeçalho — confira abaixo antes de importar.' : 'Mapeamento da conta aplicado.') : 'Não foi possível detectar as colunas: informe o mapeamento.'}</div>
    <div className="form">{col('date', 'Data *')}{col('description', 'Histórico/descrição')}{col('amount', 'Valor (com sinal)')}{col('debit', 'Débito')}{col('credit', 'Crédito')}{col('doc', 'Documento')}</div>
    {pv.lines && <><p className="muted">{pv.line_count} linhas válidas · entradas {brl(pv.total_in)} · saídas {brl(pv.total_out)} · {pv.duplicates} já importadas · {pv.skipped.length} ignoradas</p>
      <table><thead><tr><th>Data</th><th>Histórico</th><th>Doc.</th><th className="num">Valor</th></tr></thead><tbody>{pv.lines.map((l: any, i: number) => <tr key={i}><td>{date(l.line_date)}</td><td>{l.description}</td><td>{l.doc_ref}</td><td className="num">{brl(l.amount)}</td></tr>)}</tbody></table></>}
    <label className="chk" style={{ marginTop: 8 }}><input type="checkbox" checked={save} onChange={(e) => setSave(e.target.checked)} />Salvar este mapeamento para a conta</label><Err e={err} />
    <div className="right"><button onClick={onClose}>Cancelar</button><button className="primary" disabled={!pv.line_count} onClick={() => onImport(save).catch((e) => setErr(e.message))}>Importar {pv.line_count ?? 0} linhas</button></div></Modal>;
}
function LineModal({ line, onClose, onDone }: { line: any; onClose(): void; onDone(): void }) {
  const [c, setC] = useState<any>(null); const [err, setErr] = useState(''); const [adj, setAdj] = useState<any>({ interest: '', fine: '', fee: '', discount: '' }); const [kind, setKind] = useState(num(line.amount) < 0 ? 'tarifa' : 'rendimento');
  useEffect(() => { get(`/reconciliation/lines/${line.id}/candidates`).then(setC); }, []);
  const run = async (fn: () => Promise<any>) => { setErr(''); try { await fn(); onDone(); } catch (e) { setErr((e as ApiError).message); } };
  const adjBody = Object.fromEntries(Object.entries(adj).filter(([, v]) => v !== '').map(([k, v]) => [k, num(v)]));
  return <Modal onClose={onClose}><h2 style={{ marginTop: 0 }}>Conciliar linha</h2><p><b>{date(line.line_date)}</b> · {line.description} · <b style={{ color: num(line.amount) < 0 ? 'var(--red)' : 'var(--green)' }}>{brl(line.amount)}</b></p>
    {c && <>
      <h3>Movimentos do ERP com o mesmo valor</h3><table><tbody>{c.movements.map((m: any) => <tr key={m.id}><td>{date(m.movement_date)}</td><td>{m.description}</td><td>{m.kind}</td><td><button className="primary" onClick={() => run(() => api('POST', `/reconciliation/lines/${line.id}/match-movement`, { movement_id: m.id }))}>vincular</button></td></tr>)}{!c.movements.length && <tr><td className="muted">Nenhum.</td></tr>}</tbody></table>
      <h3>Títulos em aberto sugeridos ({num(line.amount) > 0 ? 'a receber' : 'a pagar'})</h3>
      <table><tbody>{c.titles.map((t: any) => <tr key={t.id}><td>{date(t.due_date)}</td><td>{t.customer_name ?? t.supplier_name ?? t.payee_name}</td><td>{t.description}</td><td className="num">{brl(t.outstanding)}</td><td>{t.exact && <span className="pill green">valor exato</span>}</td><td><button className="primary" onClick={() => run(() => api('POST', `/reconciliation/lines/${line.id}/settle`, { kind: t.kind, doc_id: t.id, ...adjBody }))}>baixar</button></td></tr>)}{!c.titles.length && <tr><td className="muted">Nenhum.</td></tr>}</tbody></table>
      <div className="toolbar"><span className="muted">Ajustes da baixa (se o valor do extrato diferir): </span>{['interest', 'fine', 'fee', 'discount'].map((k) => <input key={k} style={{ width: 100 }} type="number" step="0.01" placeholder={{ interest: 'juros', fine: 'multa', fee: 'taxa', discount: 'desconto' }[k]} value={adj[k]} onChange={(e) => setAdj({ ...adj, [k]: e.target.value })} />)}</div>
      <h3>Sem contrapartida: criar lançamento</h3><div className="toolbar"><select style={{ width: 180 }} value={kind} onChange={(e) => setKind(e.target.value)}>{['tarifa', 'juros', 'rendimento', 'aplicacao', 'resgate', 'ajuste'].map((k) => <option key={k}>{k}</option>)}</select><button onClick={() => run(() => api('POST', `/reconciliation/lines/${line.id}/create-movement`, { kind }))}>Criar e conciliar</button>
        <button className="danger" onClick={() => { const note = prompt('Motivo para ignorar:'); if (note) run(() => api('POST', `/reconciliation/lines/${line.id}/ignore`, { note })); }}>Ignorar linha</button></div></>}<Err e={err} /><div className="right"><button onClick={onClose}>Fechar</button></div></Modal>;
}

// ---------------------------------------------------------------- Fluxo de caixa
export function CashFlow() {
  const [h, setH] = useState(30); const [d, setD] = useState<any>(null); const [err, setErr] = useState(''); const [mode, setMode] = useState<'previsto' | 'projetado' | 'realizado'>('projetado');
  useEffect(() => { get('/finance/cashflow' + qs({ horizon: h })).then(setD).catch((e) => setErr(e.message)); }, [h]);
  const pts = useMemo(() => (d ? d.series.map((s: any) => ({ x: s.bucket, p: s.balance_planned, j: s.balance_projected })) : []), [d]);
  const chart = () => {
    if (!d || pts.length < 2) return null; const W = 900, H = 220, pad = 40; const all = pts.flatMap((p: any) => [p.p, p.j, 0]); const min = Math.min(...all), max = Math.max(...all); const sx = (i: number) => pad + (i / (pts.length - 1)) * (W - pad * 2); const sy = (v: number) => H - pad / 2 - ((v - min) / (max - min || 1)) * (H - pad);
    const line = (k: 'p' | 'j') => pts.map((p: any, i: number) => `${sx(i)},${sy(p[k])}`).join(' ');
    return <svg viewBox={`0 0 ${W} ${H}`} style={{ width: '100%', background: '#fff', border: '1px solid var(--line)', borderRadius: 12 }} role="img" aria-label="Saldo previsto e projetado"><line x1={pad} x2={W - pad} y1={sy(0)} y2={sy(0)} stroke="#94a3b8" strokeDasharray="4 4" /><text x={4} y={sy(0) + 4} fontSize="10" fill="#64748b">0</text>
      <polyline fill="none" stroke="#94a3b8" strokeWidth="2" strokeDasharray="6 4" points={line('p')} /><polyline fill="none" stroke="#2563eb" strokeWidth="2.5" points={line('j')} />
      <text x={pad} y={14} fontSize="11" fill="#2563eb">— projetado</text><text x={pad + 90} y={14} fontSize="11" fill="#64748b">- - previsto (contratual)</text><text x={W - pad} y={H - 4} fontSize="10" textAnchor="end" fill="#64748b">{pts[pts.length - 1].x}</text><text x={pad} y={H - 4} fontSize="10" fill="#64748b">{pts[0].x}</text></svg>;
  };
  return <><h1>Fluxo de caixa</h1><p className="sub">Realizado (movimentos), previsto (vencimentos dos títulos em aberto) e projetado (previsto ajustado pelo atraso e taxa de recebimento observados no histórico).</p><Err e={err} />
    <div className="toolbar">{[[0, 'Hoje'], [7, '7 dias'], [30, '30 dias'], [60, '60 dias'], [90, '90 dias'], [365, '12 meses']].map(([v, l]) => <button key={v} className={h === v ? 'primary' : ''} onClick={() => setH(v as number)}>{l}</button>)}<span style={{ flex: 1 }} />{(['realizado', 'previsto', 'projetado'] as const).map((m) => <button key={m} className={mode === m ? 'primary' : ''} onClick={() => setMode(m)}>{m}</button>)}</div>
    {d && <><div className="grid kpis" style={{ marginBottom: 12 }}><div className="card kpi"><div className="v">{brl(d.opening_balance)}</div><div className="l">Saldo atual (bancos + caixa)</div></div><div className="card kpi"><div className="v" style={{ color: d.min_projected_balance.value < 0 ? 'var(--red)' : undefined }}>{brl(d.min_projected_balance.value)}</div><div className="l">Menor saldo projetado ({d.min_projected_balance.date})</div></div>
      <div className="card kpi"><div className="v" style={{ fontSize: 20 }}>{d.series.length ? brl(d.series[d.series.length - 1].balance_projected) : '—'}</div><div className="l">Saldo projetado no fim do período</div></div><div className="card kpi"><div className="v" style={{ fontSize: 20 }}>{d.projection.confidence}</div><div className="l">Confiança da projeção</div></div></div>
      {d.negative_from && <div className="alert red">O saldo projetado fica negativo a partir de {d.negative_from}.</div>}<div className="alert yellow">{d.projection.note}</div>
      {mode !== 'realizado' && chart()}
      <table style={{ marginTop: 12 }}>{mode === 'realizado' ? <><thead><tr><th>{d.bucket === 'mês' ? 'Mês' : 'Dia'}</th><th className="num">Entradas</th><th className="num">Saídas</th><th className="num">Líquido</th></tr></thead><tbody>{d.realized.map((r: any) => <tr key={r.bucket}><td>{r.bucket}</td><td className="num">{brl(r.inflow)}</td><td className="num">{brl(r.outflow)}</td><td className="num">{brl(r.inflow - r.outflow)}</td></tr>)}{!d.realized.length && <tr><td className="muted" colSpan={4}>Sem movimentos no período anterior.</td></tr>}</tbody></> :
        <><thead><tr><th>{d.bucket === 'mês' ? 'Mês' : 'Dia'}</th><th className="num">Entradas</th><th className="num">Saídas</th><th className="num">Saldo</th></tr></thead><tbody>{d.series.filter((s: any) => mode === 'previsto' ? s.planned_in || s.planned_out : s.projected_in || s.projected_out || true).map((s: any) => <tr key={s.bucket}><td>{s.bucket}</td><td className="num">{brl(mode === 'previsto' ? s.planned_in : s.projected_in)}</td><td className="num">{brl(mode === 'previsto' ? s.planned_out : s.projected_out)}</td><td className="num" style={{ color: (mode === 'previsto' ? s.balance_planned : s.balance_projected) < 0 ? 'var(--red)' : undefined }}>{brl(mode === 'previsto' ? s.balance_planned : s.balance_projected)}</td></tr>)}</tbody></>}</table></>}</>;
}

// ---------------------------------------------------------------- Comissões
export function Commissions() {
  const { can } = useAuth(); const [p, setP] = useState<any>({ items: [] }); const [cl, setCl] = useState<any[]>([]); const [due, setDue] = useState(''); const [msg, setMsg] = useState(''); const [err, setErr] = useState('');
  const load = () => { get('/commissions/pending').then(setP); get('/commissions/closings').then((r) => setCl(r.items)); }; useEffect(() => { load(); }, []);
  return <><h1>Comissões de vendedores / representantes</h1><p className="sub">Comissão calculada em cada venda concluída. O fechamento gera uma conta a pagar ao vendedor e marca as vendas, evitando pagamento em duplicidade.</p>{msg && <div className="alert green">{msg}</div>}<Err e={err} />
    {can('finance:approve') && <div className="toolbar"><label>Vencimento do pagamento</label><input type="date" style={{ maxWidth: 170 }} value={due} onChange={(e) => setDue(e.target.value)} /></div>}
    <table><thead><tr><th>Vendedor</th><th className="num">Vendas</th><th className="num">Faturamento</th><th className="num">Comissão</th><th>Período</th><th /></tr></thead><tbody>
      {p.items.map((r: any) => <tr key={r.seller_id}><td>{r.name}</td><td className="num">{r.sales}</td><td className="num">{brl(r.revenue)}</td><td className="num"><b>{brl(r.commission)}</b></td><td>{date(r.first_sale)} a {date(r.last_sale)}</td>
        <td>{can('finance:approve') && <button className="primary" disabled={!due} onClick={() => { setErr(''); api('POST', '/commissions/close', { seller_id: r.seller_id, up_to: p.up_to, due_date: due }).then(() => { setMsg(`Fechamento de ${r.name} gerado e enviado ao contas a pagar.`); load(); }).catch((e) => setErr(e.message)); }}>Fechar e gerar pagamento</button>}</td></tr>)}
      {!p.items.length && <tr><td colSpan={6} className="muted">Nenhuma comissão pendente.</td></tr>}</tbody></table>
    <h3>Fechamentos anteriores</h3><table><thead><tr><th>Data</th><th>Vendedor</th><th>Até</th><th className="num">Vendas</th><th className="num">Total</th><th>Pagamento</th></tr></thead><tbody>{cl.map((c) => <tr key={c.id}><td>{date(c.created_at)}</td><td>{c.seller_name}</td><td>{date(c.up_to)}</td><td className="num">{c.sales_count}</td><td className="num">{brl(c.total)}</td><td><Tag s={c.payable_status ?? 'aberto'} /></td></tr>)}</tbody></table></>;
}

// ---------------------------------------------------------------- Configurações financeiras
export function FinanceSettings() {
  const { can } = useAuth(); const { accounts } = useAccounts(); const [s, setS] = useState<any>(null); const [msg, setMsg] = useState('');
  useEffect(() => { get('/finance/settings').then(setS); }, []); if (!s) return null; const edit = can('finance:approve');
  return <><h1>Configurações financeiras</h1><p className="sub">Cobrança em atraso e contas padrão para baixa automática de vendas à vista.</p>
    <div className="card"><div className="form"><div><label>Multa por atraso (% — cobrada uma vez)</label><input type="number" step="0.01" disabled={!edit} value={s.fine_pct} onChange={(e) => setS({ ...s, fine_pct: e.target.value })} /></div><div><label>Juros de mora (% ao mês, pro rata dia)</label><input type="number" step="0.01" disabled={!edit} value={s.interest_monthly_pct} onChange={(e) => setS({ ...s, interest_monthly_pct: e.target.value })} /></div><div><label>Carência (dias)</label><input type="number" disabled={!edit} value={s.grace_days} onChange={(e) => setS({ ...s, grace_days: e.target.value })} /></div></div>
      <p className="muted">Padrão de mercado adotado: multa de 2% + juros de 1% ao mês. Para clientes pessoa física, o Código de Defesa do Consumidor limita a multa a 2%.</p>
      <h3>Baixa automática na venda (conta que recebe cada forma de pagamento)</h3><div className="form">{[['pix', 'Pix'], ['cartao_debito', 'Cartão de débito'], ['dinheiro', 'Dinheiro']].map(([k, l]) => <div key={k}><label>{l}</label><select disabled={!edit} value={s.default_accounts?.[k] ?? ''} onChange={(e) => { const da = { ...s.default_accounts }; if (e.target.value) da[k] = e.target.value; else delete da[k]; setS({ ...s, default_accounts: da }); }}><option value="">Não baixar automaticamente (fica em aberto)</option>{accounts.filter((a) => a.active && a.kind !== 'aplicacao').map((a) => <option key={a.id} value={a.id}>{a.name}</option>)}</select></div>)}</div>
      <p className="muted">Sem conta padrão, o título nasce em aberto e é baixado manualmente ou pela conciliação do extrato. Cartão de crédito e boleto sempre ficam em aberto até o recebimento.</p>
      {edit && <div className="right"><span className="muted">{msg}</span><button className="primary" onClick={() => api('PUT', '/finance/settings', { fine_pct: num(s.fine_pct), interest_monthly_pct: num(s.interest_monthly_pct), grace_days: num(s.grace_days), default_accounts: s.default_accounts }).then(() => setMsg('Salvo.')).catch((e) => setMsg(e.message))}>Salvar</button></div>}</div></>;
}
void pct;
